import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import PollItem from "@/components/PollItem";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Eliteserien Voting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl text-black font-semibold">Aktive polls</h1>
        <br></br>

        <div className="grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-6">
          <PollItem></PollItem>
          <PollItem></PollItem>
          <PollItem></PollItem>
          <PollItem></PollItem>
          <PollItem></PollItem>
          <PollItem></PollItem>
        </div>
      </main>
    </>
  );
}
