import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Eliteserien Voting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/output.css" rel="stylesheet"/>
      </Head>

      <main className={styles.main}>

      <div className="w-full mx-12 space-y-5"> {/*mx fungerer ikke som den skal, hvis denne div blir fikset fjern w-x i children.*/}
        {/*Video 1*/}
        <div className="w-full shadow-lg bg-neutral-200 flex">
          <div className="box-content h-52 w-2/5 hover:box-content bg-black border-2 border-cyan-600"></div>
            <div className="space-x-4 space-y-8">
              <div className="align-top text-small text-neutral-500">event date | event time</div>
              <div className="align-middle text-black font-semibold">Video title</div>
              <div className="align-bottom text-small text-neutral-500">Video origin</div>
          </div>
        </div>

        {/*Video 2*/}
        <div className="w-full shadow-lg bg-neutral-200 flex">
          <div className="box-content h-52 w-2/5 hover:box-content bg-black border-2 border-cyan-600"></div>
            <div className="space-x-4 space-y-8">
              <div className="mb-1 w-1/1 align-top text-small text-neutral-500">event date | event time</div>
              <div className="w-1/1 align-middle text-black font-semibold">Video title</div>
              <div className="w-1/1 align-bottom text-small text-neutral-500">Video origin</div>
          </div>
        </div>
        
        {/*Video 3*/}
        <div className="w-full shadow-lg bg-neutral-200 flex">
          <div className="box-content h-52 w-2/5 hover:box-content bg-black border-2 border-cyan-600"></div>
            <div className="space-x-4 space-y-8">
              <div className="align-top text-small text-neutral-500">event date | event time</div>
              <div className="align-middle text-black font-semibold">Video title</div>
              <div className="align-bottom text-small text-neutral-500">Video origin</div>
          </div>
        </div>

        {/*Video 4*/}
        <div className="w-full shadow-lg bg-neutral-200 flex">
          <div className="box-content h-52 w-2/5 hover:box-content bg-black border-2 border-cyan-600"></div>
            <div className="space-x-4 space-y-8">
              <div className="mb-1 w-1/1 align-top text-small text-neutral-500">event date | event time</div>
              <div className="w-1/1 align-middle text-black font-semibold">Video title</div>
              <div className="w-1/1 align-bottom text-small text-neutral-500">Video origin</div>
          </div>
        </div>
      </div>
      


      {/* To be removed.
      Kept for easy access, and the logo looks good:).*/}
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
